[package]
name = "qurop"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
directories = "5.0.1"
env_logger = "0.10"
log = "0.4"
thiserror = "1.0"
x11rb = "0.12.0"
